# Generated by Django 5.2.4 on 2025-08-27 16:52

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fuente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nombre_pila', models.CharField(default='default', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoConsolidado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoFuente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('peso', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=20)),
                ('estado', models.CharField(default='pendiente', max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='perfiles/')),
                ('consultas_disponibles', models.PositiveIntegerField(default=0)),
                ('plan', models.CharField(choices=[('basico', 'Básico'), ('premium', 'Premium')], default='basico', max_length=50)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('estado', models.CharField(default='pendiente', max_length=20)),
                ('mensaje', models.TextField(blank=True)),
                ('archivo', models.CharField(blank=True, max_length=255)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.consulta')),
                ('fuente', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='core.fuente')),
            ],
        ),
        migrations.CreateModel(
            name='Consolidado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='consolidados/')),
                ('qr', models.ImageField(blank=True, null=True, upload_to='qrs/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consolidados', to='core.consulta')),
                ('tipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consolidados', to='core.tipoconsolidado')),
            ],
        ),
        migrations.AddField(
            model_name='fuente',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuentes', to='core.tipofuente'),
        ),
    ]
