# Generated by Django 5.2.4 on 2025-08-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuente',
            name='nombre_pila',
            field=models.CharField(max_length=100),
        ),
    ]
