# Generated by Django 5.2.4 on 2025-08-27 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_fuente_nombre_pila'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('cedula', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tipo_doc', models.CharField(blank=True, max_length=10, null=True)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('fecha_expedicion', models.DateField(blank=True, null=True)),
                ('tipo_persona', models.CharField(blank=True, max_length=50, null=True)),
                ('sexo', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
