# Generated by Django 5.2.4 on 2025-08-27 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_candidato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='cedula',
        ),
        migrations.AddField(
            model_name='consulta',
            name='candidato',
            field=models.ForeignKey(db_column='cedula', default=100381826, on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='core.candidato'),
            preserve_default=False,
        ),
    ]
