# Generated by Django 5.2.4 on 2025-08-27 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_consulta_cedula_consulta_candidato'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipofuente',
            name='nivel_consecuencia',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='tipofuente',
            name='nivel_exposicion',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
