# Generated by Django 5.2.4 on 2025-08-27 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_tipofuente_nivel_consecuencia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipofuente',
            name='peso',
        ),
    ]
