# Generated by Django 5.2.4 on 2025-08-28 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_tipofuente_peso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultado',
            name='fuente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='core.fuente'),
        ),
    ]
