# Generated by Django 5.2.4 on 2025-09-08 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_resultado_fuente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultado',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
