# Generated by Django 5.2.4 on 2025-09-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_resultado_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipofuente',
            old_name='nivel_exposicion',
            new_name='peso',
        ),
        migrations.RemoveField(
            model_name='tipofuente',
            name='nivel_consecuencia',
        ),
        migrations.AddField(
            model_name='tipofuente',
            name='probabilidad',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
