# Generated by Django 5.2.4 on 2025-09-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_nivel_exposicion_tipofuente_peso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='email',
            field=models.EmailField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='profesion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='plan',
            field=models.CharField(choices=[('sin_plan', 'Sin Plan'), ('premium', 'Premium'), ('contratista', 'Contratista')], default='sin_plan', max_length=50),
        ),
    ]
