# Generated by Django 5.2.4 on 2025-09-18 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_candidato_email_candidato_profesion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='candidato',
            field=models.OneToOneField(blank=True, db_column='cedula_candidato', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_vinculado', to='core.candidato'),
        ),
    ]
