# Generated by Django 5.2.4 on 2025-11-20 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_perfil_candidato'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='fuente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas', to='core.fuente'),
        ),
    ]
