# Generated by Django 5.2.4 on 2025-11-21 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '000X_tipo_consolidado_default'),
        ('core', '0012_consulta_fuente'),
    ]

    operations = [
    ]
