import os, urllib.parse, random, asyncio
from datetime import datetime
from playwright.async_api import async_playwright
from django.conf import settings
from asgiref.sync import sync_to_async
from core.models import Resultado, Fuente

URL = "https://www.state.gov/reports/section-353-corrupt-and-undemocratic-actors-report-2024/"
NOMBRE_SITIO = "state_section_353"


UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36")
HEADERS = {"Accept-Language": "en-US,en;q=0.9", "Upgrade-Insecure-Requests": "1"}

async def _anti_automation(page):
    await page.add_init_script("Object.defineProperty(navigator, 'webdriver', { get: () => undefined });")

async def _aceptar_cookies(page):
    for sel in ["button.cmplz-btn.cmplz-accept","div.cmplz-buttons >> button:has-text('Accept')","#onetrust-accept-btn-handler","button:has-text('Accept')"]:
        try: await page.locator(sel).first.click(timeout=2000); return True
        except Exception: pass
    return False

async def _intentarlo(browser, url, nombre, out_path):
    ctx = await browser.new_context(viewport={"width": 1400,"height":900},user_agent=UA,locale="en-US",
                                   timezone_id="America/New_York",extra_http_headers=HEADERS)
    page = await ctx.new_page()
    await _anti_automation(page)
    await page.goto(url, timeout=120000, wait_until="domcontentloaded")
    try: await page.wait_for_load_state("networkidle", timeout=15000)
    except Exception: pass
    await _aceptar_cookies(page)
    await asyncio.sleep(0.8)

    try: await page.locator("button.nav__search-trigger").click(timeout=8000)
    except Exception:
        await page.wait_for_timeout(1000)
        try: await page.locator("button.nav__search-trigger").click(timeout=8000)
        except Exception:
            await page.screenshot(path=out_path, full_page=True)
            await ctx.close()
            return False

    await page.fill("#nav__search-query", nombre or "")
    await page.keyboard.press("Enter")
    try: await page.wait_for_url("**search.state.gov**", timeout=20000)
    except Exception: pass
    try: await page.wait_for_load_state("networkidle", timeout=15000)
    except Exception: await page.wait_for_timeout(3000)
    await page.screenshot(path=out_path, full_page=True)
    await ctx.close()
    return True

# --- helper para detectar el 403 de CloudFront (igual al del otro bot) ---
async def _is_cloudfront_block(page) -> bool:
    try:
        body = (await page.inner_text("body", timeout=2000)).lower()
    except Exception:
        body = ""
    needles = [
        "403 error",
        "the request could not be satisfied",
        "request blocked",
        "generated by cloudfront (cloudfront)",
        "cloudfront documentation",
    ]
    return any(n in body for n in needles)

async def consultar_state_section_353_pdf(consulta_id: int, nombre: str, cedula: str):
    """Busca en state.gov (sección 353), guarda PNG de evidencia y clasifica.
       - Si aparece el 403 de CloudFront → Sin validar + mensaje claro
       - Si hay resultados → Validada (score 10)
       - Si no → Validada (score 0) con mensaje de no hallazgos
       - En error → Sin validar con evidencia si existe
    """
    # Rutas de salida
    rel_dir = os.path.join("resultados", str(consulta_id))
    abs_dir = os.path.join(settings.MEDIA_ROOT, rel_dir)
    os.makedirs(abs_dir, exist_ok=True)
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    out_png_abs = os.path.join(abs_dir, f"{NOMBRE_SITIO}_{cedula}_{ts}.png")
    out_png_rel = os.path.join(rel_dir, os.path.basename(out_png_abs))

    # Fuente
    try:
        fuente_obj = await sync_to_async(Fuente.objects.get)(nombre=NOMBRE_SITIO)
    except Exception as e:
        await sync_to_async(Resultado.objects.create)(
            consulta_id=consulta_id, fuente=None, score=0,
            estado="Sin validar",
            mensaje=f"No se encontró la Fuente '{NOMBRE_SITIO}': {e}",
            archivo=""
        )
        return

    navegador = ctx = page = None
    try:
        async with async_playwright() as p:
            navegador = await p.chromium.launch(
                headless=True,
                args=["--disable-blink-features=AutomationControlled"]
            )
            ctx = await navegador.new_context(
                viewport={"width": 1400, "height": 900},
                user_agent=UA,
                locale="en-US",
                timezone_id="America/New_York",
                extra_http_headers=HEADERS,
            )
            page = await ctx.new_page()
            await _anti_automation(page)

            # 1) Abrir la sección 353
            await page.goto(URL, timeout=120000, wait_until="domcontentloaded")
            try: await page.wait_for_load_state("networkidle", timeout=15000)
            except Exception: pass
            await _aceptar_cookies(page)

            # 2) Abrir buscador global y consultar el nombre
            try:
                await page.locator("button.nav__search-trigger").click(timeout=8000)
            except Exception:
                await page.wait_for_timeout(800)
                await page.locator("button.nav__search-trigger").click(timeout=8000)

            await page.fill("#nav__search-query", (nombre or "").strip())
            await page.keyboard.press("Enter")

            # 3) Esperar SERP
            try: await page.wait_for_url("**search.state.gov**", timeout=20000)
            except Exception: pass
            try: await page.wait_for_load_state("networkidle", timeout=15000)
            except Exception: pass
            await page.wait_for_timeout(800)

            # 4) Evidencia SIEMPRE
            await page.screenshot(path=out_png_abs, full_page=True)

            # 5) CloudFront 403 → Sin validar
            if await _is_cloudfront_block(page):
                await ctx.close(); await navegador.close()
                await sync_to_async(Resultado.objects.create)(
                    consulta_id=consulta_id, fuente=fuente_obj,
                    score=0, estado="Sin validar",
                    mensaje="La fuente bloqueó la solicitud (CloudFront 403: Request blocked). Intenta más tarde.",
                    archivo=out_png_rel
                )
                return

            # 6) Clasificar resultados
            body_txt = ""
            try:
                body_txt = (await page.inner_text("body", timeout=3000)).strip()
            except Exception:
                body_txt = ""
            low = body_txt.lower()

            # patrón de “no results”
            nores = any(s in low for s in [
                "no results", "no results found", "we couldn’t find", "we couldn't find"
            ])

            has_results = False
            if not nores:
                for sel in [
                    "#results", ".search-results", "ol.search-results",
                    "article", ".gsc-results", "main .result", ".search__results"
                ]:
                    try:
                        if await page.locator(sel).first.count() > 0:
                            has_results = True
                            break
                    except Exception:
                        pass

            if nores:
                score = 0
                mensaje = "No se encontraron resultados para la búsqueda."
            elif has_results:
                score = 10
                mensaje = "Se encontraron resultados para la búsqueda."
            else:
                score = 0
                mensaje = "No fue posible determinar resultados; revisar evidencia."

            await ctx.close(); await navegador.close()

        # 7) Guardar en BD
        await sync_to_async(Resultado.objects.create)(
            consulta_id=consulta_id, fuente=fuente_obj,
            score=score, estado="Validada",
            mensaje=mensaje, archivo=out_png_rel
        )

    except Exception:
        # Evidencia si no existe
        try:
            if page is not None and not os.path.exists(out_png_abs):
                await page.screenshot(path=out_png_abs, full_page=True)
        except Exception:
            pass
        try:
            if ctx is not None: await ctx.close()
        except Exception:
            pass
        try:
            if navegador is not None: await navegador.close()
        except Exception:
            pass

        await sync_to_async(Resultado.objects.create)(
            consulta_id=consulta_id, fuente=fuente_obj,
            score=0, estado="Sin validar",
            mensaje="La fuente no se ha podido consultar en este momento.",
            archivo=out_png_rel if os.path.exists(out_png_abs) else ""
        )